### ISSUE TITLE
Error starting Towny (MYSQL)

### ISSUE THREAD

**Issue by JohOply** [LlmDl/Towny#2393]
Hi

I want uptodate Towny (0.89.2.0 > 0.90.0.0) and i have this error. I also tried without any data in mysql, same error. I use Spigot 1.8.8-b565.

http://pastebin.com/6aY2scVF

**Comment by LlmDl** [comment]
What's up with your language file? Are you not using the default one?

**Comment by JohOply** [comment]
I don't know, it work perfectly with 0.89.2.0. It is a french translation : http://pastebin.com/JXLRzFAu

**Comment by LlmDl** [comment]
It will be missing the new language strings. If you're able to translate them I'd be glad to add your new language file to Towny.

**Comment by JohOply** [comment]
I will see into it when i have some time, i hadn't try yet default translation

**Comment by JohOply** [comment]
I don't understand, i don't see any difference between 0.23 and 0.24 version language... Could you help me please ?

**Comment by LlmDl** [comment]
This link has the commit where the language file went from .23 to .24, it isnt very much
https://github.com/LlmDl/Towny/commit/2029cf2e67ce6e7a306158941dfe809f16bb3cae

**Comment by JohOply** [comment]
It is already in my french file... Strange

**Comment by LlmDl** [comment]
Pastebin.com your current french.yml

**Comment by JohOply** [comment]
http://pastebin.com/YXj0yqkJ

**Comment by LlmDl** [comment]
And can you please pastebin.com your current startup using that file

**Comment by JohOply** [comment]
[16:44:00 INFO]: [Towny] Enabling Towny v0.90.0.0
[16:44:00 INFO]: ====================      Towny      ========================
[16:44:00 WARN]: java.io.IOException
[16:44:00 WARN]: at com.palmergames.util.FileMgmt.convertStreamToString(FileMgmt.java:157)
[16:44:00 WARN]: at com.palmergames.bukkit.towny.TownySettings.loadLanguage(TownySettings.java:236)
[16:44:00 WARN]: at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:254)
[16:44:00 WARN]: at com.palmergames.bukkit.towny.Towny.load(Towny.java:206)
[16:44:00 WARN]: at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:101)
[16:44:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:44:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:44:00 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:44:00 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[16:44:00 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[16:44:00 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[16:44:00 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[16:44:00 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[16:44:00 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[16:44:00 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[16:44:00 WARN]: at java.lang.Thread.run(Thread.java:745)
[16:44:00 INFO]: =============================================================
[16:44:00 INFO]: [WARNING] - ***** SAFE MODE ***** 0.90.0.0
[16:44:00 INFO]: =============================================================

**Comment by LlmDl** [comment]
You ought to try replacing all the accented e's and other letters with the regular letter.

**Comment by JohOply** [comment]
Without any é è à ù, same error : http://pastebin.com/NGiczb1f
Like i told you, the file work perfectly in 0.89.2.0 :/

**Comment by JohOply** [comment]
Hi!
Any news about my problem? :/

**Comment by JohOply** [comment]
Hi guy

I havn't any news about that since a lot of months... I can understand that i done something wrong, but i think you can at least explain me what can i do...

**Comment by LlmDl** [comment]
All the pastebins for this ticket have expired so I cannot say what happened. Make a new ticket, be sure you're up to date and you include pastebin.com's of the full server startup, your towny config.yml and you language file.
