### ISSUE TITLE
Towny throwing errors when players Log in

### ISSUE THREAD

**Issue by Buckmanfu** [LlmDl/Towny#2413]
2016-01-04 19:20:03 [INFO] UUID of player ####### is #############################
2016-01-04 19:20:03 [INFO]########[/###.###.###.###:########] logged in with entity id 4484 at ([world]9042.638594152339, 48.88092236864216, -364.4979693618154)
2016-01-04 19:20:03 [WARN] [Towny] Task #1554 for Towny v0.90.0.0 generated an exception
java.lang.NullPointerException
        at com.palmergames.bukkit.towny.tasks.SetDefaultModes.run(SetDefaultModes.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by LlmDl** [comment]
please pastebin.com the entire startup sequence and link it here

**Comment by Buckmanfu** [comment]
here it is

http://pastebin.com/5BazcnYD

thanks for looking into this

**Comment by LlmDl** [comment]
Your permission plugin ZAdminPermissions doesn't appear to support option/info nodes.

**Comment by Buckmanfu** [comment]
If there error from Towny was more meaning full, I would take it up with the author of ZAdminPermission.  

More than likely from the extensive list of plugins that work just fine, this is a Towny issue, even if the issue the meaningless error it's throwing, rather than an Error that indicates what Towny is Expecting and didn't get.

**Comment by Zhro** [comment]
I'm not familiar with the Towny codebase but it would appear at first glance that code at line 33:

`String modeString = TownyUniverse.getPermissionSource().getPlayerPermissionStringNode(name, PermissionNodes.TOWNY_DEFAULT_MODES.getNode());`

.. is supposed to fallback on `TOWNY_DEFAULT_MODES` if the permissions plugin does not support Info/Option extensions; these appear to be unique to GroupManager and PEX and not a feature of Bukkit.

**Comment by LlmDl** [comment]
info/option nodes have been used by all major permission plugins including GM, pex, bperms and I'm sure many newer plugins. They are used for chat channels and also other mode options in towny unrelated to chat.

**Comment by Zhro** [comment]
So it's not a bug that `TOWNY_DEFAULT_MODES` isn't being evaluated by `getPlayerPermissionStringNode()`?

Our permissions plugin is deeply integrated with our payment processing system and we're unable to change it at this time.

Would you please simply add support for default modes or just add a check to see if the return type is null? Info/Options is not part of the Bukkit permissions API; I don't see why you're suggesting that we perform a major refactoring of our servers to support something that can be easy handled in a config file.

**Comment by LlmDl** [comment]
Give this a test for me. https://dl.dropboxusercontent.com/u/31426972/Towny.jar

Long-term you might want to get that permission plugin set up with the ability to handle option/info nodes.

**Comment by Zhro** [comment]
Confirmed working. Thank you.
