### ISSUE TITLE
Task #338 for TownyChat v0.45 generated an exception

### ISSUE THREAD

**Issue by ShadyEntry** [LlmDl/Towny#2426]
[03:36:39] [Server thread/WARN]: [TownyChat] Task #338 for TownyChat v0.45 generated an exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_72]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.setConfigs(ConfigurationHandler.java:379) ~[?:?]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.saveConfig(ConfigurationHandler.java:316) ~[?:?]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.loadConfig(ConfigurationHandler.java:298) ~[?:?]
	at com.palmergames.bukkit.TownyChat.tasks.onLoadedTask.run(onLoadedTask.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6d16e64-87b9f46]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-87b9f46]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-87b9f46]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Towny isn't loading chat configs. Any idea why?

**Comment by LlmDl** [comment]
Pastebin.com your chatconfig.yml,
Ticket grade: D-
