### ISSUE TITLE
Townychat Not working with Deluxechat

### ISSUE THREAD

**Issue by TheExceed** [LlmDl/Towny#2445]
Before, you had to add "hooked: true" into the channels.yml for townychat to hook into deluxechat or vice versa and now it seems to be causing errors. Any fix would be great.

```
[18:43:46] [Server thread/WARN]: [TownyChat] Task #89 for TownyChat v0.45 generated an exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2227) ~[?:1.8.0_31]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.setConfigs(ConfigurationHandler.java:379) ~[?:?]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.saveConfig(ConfigurationHandler.java:316) ~[?:?]
	at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.loadConfig(ConfigurationHandler.java:298) ~[?:?]
	at com.palmergames.bukkit.TownyChat.tasks.onLoadedTask.run(onLoadedTask.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot1.9.jar:git-Spigot-3104eb1-bf43ca6]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
```

**Comment by LlmDl** [comment]
Pastebin.com your chatconfig.yml and channels.yml

**Comment by TheExceed** [comment]
http://pastebin.com/pKJuuZn1 - channels
http://pastebin.com/53ERw8Pq - chatconfig

**Comment by LlmDl** [comment]
Your chatconfig looks like its missing teh new alone message stuff. Let it generate a new one and then reconfigure it.

**Comment by TheExceed** [comment]
http://pastebin.com/wAzBxR6B is that correct then?

**Comment by LlmDl** [comment]
Yes, does deluxechat work now?

Do you still have a towny chat error in your log?

**Comment by TheExceed** [comment]
It does work, however the placeholder for it does not.

**Comment by TheExceed** [comment]
http://prntscr.com/aetfl4

**Comment by LlmDl** [comment]
That's a deluxechat issue not a townychat one.

**Comment by TheExceed** [comment]
Alrighty, thank you.
