### ISSUE TITLE
1.9.2 Towny Error

### ISSUE THREAD

**Issue by zonprox** [LlmDl/Towny#2482]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:
### What steps will reproduce the problem?
1. Install Plugin on Ubuntu x64 - Spigot 1.9.2 - Bungeecord
### Please use Pastebin.com to link the following files:

[08:43:21] [Server thread/INFO]: [Towny] Enabling Towny v0.91.1.0
[08:43:21] [Server thread/INFO]: ====================      Towny      ========================
[08:43:21] [Server thread/WARN]: java.io.IOException
[08:43:21] [Server thread/WARN]:    at com.palmergames.util.FileMgmt.convertStreamToString(FileMgmt.java:157)
[08:43:21] [Server thread/WARN]:    at com.palmergames.bukkit.towny.TownySettings.loadLanguage(TownySettings.java:238)
[08:43:21] [Server thread/WARN]:    at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:254)
[08:43:21] [Server thread/WARN]:    at com.palmergames.bukkit.towny.Towny.load(Towny.java:217)
[08:43:21] [Server thread/WARN]:    at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
[08:43:21] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[08:43:21] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[08:43:21] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:43:21] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[08:43:21] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[08:43:21] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[08:43:21] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[08:43:21] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[08:43:21] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[08:43:21] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[08:43:21] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[08:43:21] [Server thread/INFO]: =============================================================
[08:43:21] [Server thread/INFO]: [WARNING] - ****\* SAFE MODE ****\* 0.91.1.0
[08:43:21] [Server thread/INFO]: =============================================================

**Comment by LlmDl** [comment]
You skipped the form and what I needed to see is your config.yml and your language file.
