### ISSUE TITLE
Error when changing language file

### ISSUE THREAD

**Issue by Noiknez** [LlmDl/Towny#2505]
Hi, i decided to translate the english.yml file into the french.yml file but then i see that i get an error on the console and towny not functionning properly. I check the synthax, the spacing, the special caracter (i try 2 different file : with and without, same problem) also the other language issue in this github, and again i couldn't work properly

### What steps will reproduce the problem?
1. Put the Towny config.yml from http://pastebin.com/3dFnb92D
2. Put the french.yml language file from here :
With special character (é,è,à,ô,ù) : http://pastebin.com/TU3YnVax
Without any special character : http://pastebin.com/24r0nijA
(The encoding of the french.yml file is the same as the english.yml in towny folder)
3. Start the server
4. Watch the error : http://pastebin.com/ywis17tx

### What is the expected output?

1. The expected output is an error in the console : http://pastebin.com/ywis17tx
2. and the startup of towny in safe mode because it can't work with the french.yml

### What is your Towny version?
 Towny Advanced 0.91.1.0 [CB/Spigot 1.8.3+] 

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2)

1. Your full server startup from the logs\latest.log : http://pastebin.com/WMTskphh
2. Your Towny config.yml : http://pastebin.com/3dFnb92D
3. Your townyperms.yml : http://pastebin.com/QTQn0HkQ
4. Your log's error : http://pastebin.com/ywis17tx

**Comment by ThemInspectors** [comment]
Try using double quotes not single also are you using UTF-8?

**Comment by Noiknez** [comment]
When replacing single quotes with double quotes i got the same error : http://pastebin.com/Lx4vHyUq
My file are also in UTF-8 (without BOM) : http://pastebin.com/L4KFxZEX

**Comment by Noiknez** [comment]
The issue appear just when i change the name of the file and the config.yml to match the file

> [15:44:41 INFO]: [Towny] Enabling Towny v0.91.1.0
[15:44:41 INFO]: ====================      Towny      ========================
[15:44:41 WARN]: java.io.IOException
[15:44:41 WARN]:        at com.palmergames.util.FileMgmt.convertStreamToString(FileMgmt.java:157)
[15:44:41 WARN]:        at com.palmergames.bukkit.towny.TownySettings.loadLanguage(TownySettings.java:238)
[15:44:41 WARN]:        at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:254)
[15:44:41 WARN]:        at com.palmergames.bukkit.towny.Towny.load(Towny.java:217)
[15:44:41 WARN]:        at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
[15:44:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[15:44:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:44:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:44:41 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[15:44:41 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[15:44:41 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417)
[15:44:41 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382)
[15:44:41 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:337)
[15:44:41 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[15:44:41 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540)
[15:44:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:44:41 INFO]: =============================================================
[15:44:41 INFO]: [WARNING] - ***** SAFE MODE ***** 0.91.1.0
[15:44:41 INFO]: =============================================================

**Comment by LlmDl** [comment]
Change the name of the file to what?

What file? (Link it)

**Comment by Noiknez** [comment]
Sorry i forgot to link it, what i mean is that i just change the name of "english.yml" to "french.yml" http://pastebin.com/UQ2ewXFF
and change in config.yml line 21 : "english.yml" to "french.yml" http://pastebin.com/Z2brknGU

Just this two thing made the error appear http://pastebin.com/ZsUbR6j5

**Comment by LlmDl** [comment]
Fairly sure this is fixed now in 0.91.1.4, http://towny.palmergames.com/?p=895

Please note that a change to the databasehandler was made in 0.91.1.2, it has been tested lightly and no issues have been found yet but it wasn't that long ago. You may want to wait before updating your production server to 0.91.1.4 because of this.
