### ISSUE TITLE
i keep getting [10:40:09 WARN]: java.lang.NumberFormatException: For input string: "247

### ISSUE THREAD

**Issue by davidstrains96** [LlmDl/Towny#2533]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. enabling towny using plugman or rebooting the server
2.
3.

### What is the expected output?
1.[10:40:09 INFO]: ====================      Towny      ========================
[10:40:09 INFO]: Exception 
[10:40:09 INFO]: [Towny] Newer language file available, language file updated.
[10:40:09 INFO]: Exception 
[10:40:09 INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[10:40:09 WARN]: java.lang.NumberFormatException: For input string: "247�����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
[10:40:09 WARN]: ��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
[10:40:09 WARN]: ��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
[10:40:09 WARN]: �����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
[10:40:09 WARN]: �������������������������������������������������������0"
[10:40:09 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[10:40:09 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[10:40:09 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.db.TownyFlatFileSource.loadTownBlockList(TownyFlatFileSource.java:279)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:99)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.object.TownyUniverse.loadDatabase(TownyUniverse.java:326)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:277)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.Towny.load(Towny.java:217)
[10:40:09 WARN]:        at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
[10:40:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[10:40:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[10:40:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:40:09 WARN]:        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:72)
[10:40:09 WARN]:        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127)
[10:40:09 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[10:40:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:40:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:40:09 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[10:40:09 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:40:09 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[10:40:09 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[10:40:09 WARN]:        at java.lang.Thread.run(Thread.java:745)
[10:40:09 INFO]: [Towny] Error: Failed to load!
[10:40:09 INFO]: =============================================================
[10:40:09 INFO]: [WARNING] - ***** SAFE MODE ***** 0.91.1.6
[10:40:09 INFO]: =============================================================
2.
3.

### What is your Towny version?
Do not say "latest".
19.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".

1.11.0

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/abVD56ZE
3. Your townyperms.yml : http://pastebin.com/6apzKkFk
4. Your log's error :  http://pastebin.com/45ztkG5e

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
pastebin.com your towny\data\townblocks.txt file.

**Comment by davidstrains96** [comment]
http://pastebin.com/yZPhQw2x

**Comment by davidstrains96** [comment]
i am about to revise it

i found a few typos and missing things in the towny block file but it didnt fix it

**Comment by davidstrains96** [comment]
I would love to join and help you guys in developing Towny

**Comment by davidstrains96** [comment]
i just tried to let towny regenerate a new towny folder but it still didnt load

**Comment by LlmDl** [comment]
It's probably because you named your town Downtown2.0

Don't use periods in the town name

**Comment by davidstrains96** [comment]
it has worked till last night

**Comment by davidstrains96** [comment]
i dont know what has caused  this sudden issue

**Comment by davidstrains96** [comment]
I did a roll back a few days ago and towny worked with the Downtown2.0



on a side not i would like to help in any way possible with towny i am a programmer looking for a project to hellp out with

**Comment by LlmDl** [comment]
Looked at it again, 

line 5439 of your townblocks.txt is 
Downtown,3wntown,28,-48

You can't have 2 names for a world, just one.

**Comment by TekkitCommando** [comment]
@davidstrains96 You just code PR's, you don't need permission to help out :P

**Comment by LlmDl** [comment]
But skipping parts of the form, and not knowing your towny version number (even though its written a few lines above,) don't show off your programming skills.

**Comment by davidstrains96** [comment]
u guys arnt very nice

**Comment by LlmDl** [comment]
Well sorry for helping you find the problem on your server.
