### ISSUE TITLE
PlayerQuitEvent - 1.11.2 Error

### ISSUE THREAD

**Issue by VerumUK** [LlmDl/Towny#2536]
As of Minecraft version 1.11.2 I get the following error upon a player leaving the server.

[08:08:02] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Towny v0.91.1.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit_latest.jar:git-Bukkit-e232e15]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_latest.jar:git-Bukkit-e232e15]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:363) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1020) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:306) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(SourceFile:215) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:765) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit_latest.jar:git-Bukkit-e232e15]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.IllegalStateException: Cannot set scoreboard for invalid CraftPlayer
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setScoreboard(CraftPlayer.java:1278) ~[craftbukkit_latest.jar:git-Bukkit-e232e15]
	at com.palmergames.bukkit.towny.huds.HUDManager.toggleOff(HUDManager.java:68) ~[?:?]
	at com.palmergames.bukkit.towny.huds.HUDManager.toggleAllOff(HUDManager.java:64) ~[?:?]
	at com.palmergames.bukkit.towny.huds.HUDManager.onPlayerQuit(HUDManager.java:75) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit_latest.jar:git-Bukkit-e232e15]

**Comment by LlmDl** [comment]
Fixed as of 0.91.2.1
