### ISSUE TITLE
An error when registering

### ISSUE THREAD

**Issue by DanielTravi** [LlmDl/Towny#2581]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?

1. Occurs when a player enters the server for the first time and registers automatically as a resident

### What is your Towny version?

Towny 0.91.4.2

### What is your spigot/craftbukkit version?

spigot 1.11.2

### Your log's error : 

Error:
[15:04:56 INFO]: UUID of player PrestonArmy1 is 79a2781e-f64a-3d96-8317-1505ee13c906
[15:04:56 INFO]: [Bank] Loading Bank for 79a2781e-f64a-3d96-8317-1505ee13c906 from file
[15:04:56 INFO]: [Bank] Loaded Bank for 79a2781e-f64a-3d96-8317-1505ee13c906 from file, took 33 ms
[15:04:56 INFO]: [ChatAPI] Added channel for 79a2781e-f64a-3d96-8317-1505ee13c906
[15:04:57 WARN]: com.palmergames.bukkit.towny.exceptions.NotRegisteredException: The resident 'prestonarmy1' is not registered.
[15:04:57 WARN]:        at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.getResident(TownyDatabaseHandler.java:97)
[15:04:57 WARN]:        at com.palmergames.bukkit.towny.permissions.TownyPerms.assignPermissions(TownyPerms.java:102)
[15:04:57 WARN]:        at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerChangeWorld(TownyPlayerListener.java:632)
[15:04:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:04:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:04:57 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:04:57 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:04:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:04:57 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.moveToWorld(PlayerList.java:682)
[15:04:57 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:508)
[15:04:57 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:260)
[15:04:57 WARN]:        at me.leoko.login.Main.preLoginScreen(Main.java:360)
[15:04:57 WARN]:        at me.leoko.login.Events.onJoin(Events.java:243)
[15:04:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:04:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:04:57 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:04:57 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:04:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:04:57 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[15:04:57 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[15:04:57 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:04:59 INFO]: PrestonArmy1[/127.0.0.1:8604] logged in with entity id 4531 at ([Sesion]0.5, 90.0, 0.5)
[15:04:59 INFO]: [GAListener] Player: PrestonArmy1 has 0 votes
[15:05:01 INFO]: Creando configuraci¾n vacÝa: B:\TravisUniverse\TravisUniverse\plugins\Essentials\userdata\79a2781e-f64a-3d96-8317-1505ee13c906.yml

**Comment by LlmDl** [comment]
You skipped the rest of the form which would be very helpful in this situation. Resubmit your ticket.
