### ISSUE TITLE
NPE on player login, not finding town bank (CC3)

### ISSUE THREAD

**Issue by ChibbyGit** [LlmDl/Towny#2673]
### What steps will reproduce the problem?
1. Adding economy plugin. (https://www.spigotmc.org/resources/craftconomy.2395/)
2. Player joining server.
3. Towny attempting to collect town payment.

### What is the expected output?
1. Town get's charged.
2. No exceptions/issues/bugs/errors.
3. Profit?

### What is your Towny version?
Towny version: 0.91.4.11

### What is your spigot/craftbukkit version?
Paper version git-Paper-1227 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

1. Your full server startup from the logs\latest.log :
https://pastebin.com/fg8TgahL
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/ZDSh36Cy
3. Your townyperms.yml :
https://pastebin.com/n7vY7S7c
4. Your log's error : 
https://pastebin.com/VTfyWu20
5. Your permissions file :
N/A
6. Your chatconfig.yml :
N/A
7. Your channels.yml :
N/A

**Comment by LlmDl** [comment]
You could try updating your version of Vault, usually this sort of error is caused by the economy plugin not working fully.

**Comment by ChibbyGit** [comment]
Vault is up-to-date. I keep all plugins updated persistently!

**Comment by ChibbyGit** [comment]
Kind of hard to have out-of-date vault considering it has not updated in a few years. lol

**Comment by Beelzebu** [comment]
Try with another economy plugin, like iConomy

**Comment by ChibbyGit** [comment]
I can't get my hands on iConomy due to the project being in moderation on bukkit.

**Comment by LlmDl** [comment]
I have a version of my own iConomy, hosted on the towny.palmergames.com site.

**Comment by ChibbyGit** [comment]
`[15:20:58 INFO]: Chibby_ issued server command: /money
[15:20:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v5.05
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.iConomy.iConomy.onCommand(iConomy.java:215) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        ... 15 more`
