### ISSUE TITLE
Towny new day broke with no server changes

### ISSUE THREAD

**Issue by Metisuneatn** [LlmDl/Towny#2701]
Attempted to recreate it on a test server and was unable to. I think its because I don't have our current towny data on the test server

The error is on 0.91.4.11 but I updated again to v0.91.4.12. And got it again. 

spigot-7754231-94b0980 1.12.2

Towny new day for the last few days has suddenly stopped taking taxes. I have not made any changes on the server including changing towny version (till today to test it).

`[12:08:28] [Craft Scheduler Thread - 474/WARN]: [Towny] Plugin Towny v0.91.4.11 generated an exception while executing task 571
com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:111) ~[?:?]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:92) ~[?:?]
	at com.earth2me.essentials.Essentials.getOfflineUser(Essentials.java:629) ~[?:?]
	at com.earth2me.essentials.Essentials.getUser(Essentials.java:617) ~[?:?]
	at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:67) ~[?:?]
	at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:85) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:148) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:141) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:146) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:151) ~[?:?]
	-^this spams for a ton of lines-

	Caused by: java.lang.StackOverflowError
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method) ~[?:1.8.0_131]
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242) ~[?:1.8.0_131]
	at java.io.File.exists(File.java:819) ~[?:1.8.0_131]
	at com.earth2me.essentials.UserMap.load(UserMap.java:157) ~[?:?]
	at com.earth2me.essentials.UserMap.load(UserMap.java:23) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[spigot_latest.jar:git-Spigot-7754231-94b0980]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:111) ~[?:?]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:92) ~[?:?]
	at com.earth2me.essentials.Essentials.getOfflineUser(Essentials.java:629) ~[?:?]
	at com.earth2me.essentials.Essentials.getUser(Essentials.java:617) ~[?:?]
	at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:67) ~[?:?]
	at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:85) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:148) ~[?:?]
	at com.earth2me.essentials.api.Economy.add(Economy.java:141) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.depositPlayer(Economy_Essentials.java:146) ~[?:?]
	... 1003 more`

**Comment by LlmDl** [comment]
Looks like an issue with essentials eco, which has had problems for years. You skipped the form.

**Comment by Metisuneatn** [comment]
They said its a towny issue....

**Comment by LlmDl** [comment]
File a proper ticket without skipping the form.
